//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionRequest
    {
        public int ColId { get; set; }
        public Nullable<int> CrId { get; set; }
        public string FoodType { get; set; }
        public Nullable<int> MaxTime { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CempId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
