//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.CollectionRequests = new HashSet<CollectionRequest>();
        }
    
        public int Empid { get; set; }
        public string EmpName { get; set; }
        public string EmpAge { get; set; }
        public string EmpAdd { get; set; }
        public string EmpPhone { get; set; }
        public string EmpUserName { get; set; }
        public string EmpPassword { get; set; }
        public Nullable<int> EmpStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionRequest> CollectionRequests { get; set; }
    }
}
